export { DashboardRangeProvider, useDashboardRange } from './DashboardRangeContext'
export { HeaderSection } from './HeaderSection'
export { EarningsSection } from './EarningsSection'
export { GoalSection } from './GoalSection'
export { HoursSection } from './HoursSection'
export { EffectiveRateSection } from './EffectiveRateSection'
export { ActivitySection } from './ActivitySection'
export { ProjectsSection } from './ProjectsSection'
export { InvoicesSection } from './InvoicesSection'
export { QuarterlySummarySection } from './QuarterlySummarySection'
export { UpcomingSection } from './UpcomingSection'
export { QuickActionsSection } from './QuickActionsSection'
export { WeeklyGlanceSection } from './WeeklyGlanceSection'

export { Footer } from './Footer'
export { SectionHeader } from './SectionHeader'
